---
provider:
  type: 'route53'
  zone_id: 'Z627GH1M87Y192'
  credentials: './assets/conf/.aws/credentials'
  profile_name: 'dyndns'
record:
  name: 'app.contoso.com'
  type: 'A'
  ttl: 60
sync_interval: 15
